"""initial migration

Revision ID: 45b1e55b3c62
Revises: None
Create Date: 2014-01-03 16:14:36.368103

"""

# revision identifiers, used by Alembic.
revision = '45b1e55b3c62'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players_player',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('players_player')
    ### end Alembic commands ###
